apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: user
          image: listengrey/luciana-chat:latest
          envFrom:
            - configMapRef:
                name: luciana-conf
          ports:
            - containerPort: 8080